version: '3.7'

services:
    api:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - './:/usr/src/app'
        environment:
            - ENV=1